[project]
name = "pac-man"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygame",
    "pydantic>=2",
    "mypy==2.3.0",
    "mazegenerator",
]

[tool.mypy]
plugins = ["pydantic.mypy"]

[tool.uv.sources]
mazegenerator = { path = "mazegenerator-2.1.0-py3-none-any.whl" }
